### ISSUE TITLE
Scrolling in iOS 7 Safari stops animations

### ISSUE THREAD

**Issue by hotmeteor** [scottjehl/Device-Bugs#37]
## Summary:

Loading a page in Safari and then perform transitional animations works fine. However, if you scroll the page and then try an animation there are no transitions. Occurs whether you scroll before or after you attempt a transition.
## Platforms:
- Mobile Safari, iOS 7
## How to reproduce:
1. Load a page with transitions
2. Try the animation
3. Scroll
4. Try the animation again
## Reduced Example:

[http://cdpn.io/ACwxJ](http://cdpn.io/ACwxJ)
## Bug Tracker ticket(s):
- filed with Apple Bug Reporter [14196575](https://bugreport.apple.com/cgi-bin/WebObjects/RadarWeb.woa/64/wo/i8Lbwbelfdoexpnznzk7Z0/8.66)
## Workarounds:
- none at this time.

**Comment by hotmeteor** [comment]
Just an update. Apple informed me that my bug report was duplicate, and the original was closed. So we'll see what happens on the next iOS 7 update.

**Comment by scottjehl** [comment]
fingers crossed, then! fwiw, I received a similar note about the iOS orientation change zoom bug and it still took a year or two to make it into a release. Not much transparency there, unfortunately.

Thanks for filing!

**Comment by hotmeteor** [comment]
Geez. Ya, well hopefully. Seems even vital bugs don't get labelled as important to Apple.
And no prob

**Comment by hotmeteor** [comment]
Good news - iOS 7 beta 2 has resolved the transition bugs. That was nice and quick :)
Closing.
