### ISSUE TITLE
canvas.toDataURL('image/jpeg') returns image/png

### ISSUE THREAD

**Issue by nkeaton** [scottjehl/Device-Bugs#45]
I HAVE IMAGE/PNG.  HOW DO I CONVERT TO IMAGE/JPEG?

**Comment by patrickkettner** [comment]
@nkeaton stackoverflow.com would be a better place to ask this sort of a question, this is a place to list known bugs, rather than ask for clarification on issues.

Make sure to include a jsfiddle or codepen showing the problem, it makes it a lot easier to assist!

**Comment by nkeaton** [comment]
THANK YOU PATRICK

**Comment by patrickkettner** [comment]
my pleasure :D
