### ISSUE TITLE
Safari 8 (iOS 8) has broken blob URL Scheme

### ISSUE THREAD

**Issue by frontenddeveloping** [scottjehl/Device-Bugs#54]
From here - https://github.com/eligrey/FileSaver.js/issues/12#issuecomment-47429803
It means that `URL.createObjectURL` with blob will always throw an error

Example: http://jsfiddle.net/frontenddeveloping/zvsb2e98/

**Comment by frontenddeveloping** [comment]
Fixed in 8.0.2

**Comment by staabm** [comment]
Any link to a public avail bugtracker related to this (e.g. On http://bugs.webkit.org)?

**Comment by frontenddeveloping** [comment]
It seems like it was broken only in iOS 8.0.0
