### ISSUE TITLE
clicking on form elements on html5 takes me tot he top of the page

### ISSUE THREAD

**Issue by chetakagrawal** [scottjehl/Device-Bugs#67]
I am using foundation to with HTML5 elements to build a form. But clicking on some new HTML5 input types takes me to the top of the page.
This does not happen in iPad or Android. 
Can anyone tell me how to resolve this bug?

**Comment by Maybach91** [comment]
Could you please use the [ISSUE TEMPLATE](https://github.com/scottjehl/Device-Bugs/blob/master/ISSUE%20TEMPLATE)?
